name: 'app'

# The type key specifies the language and version for your application.
type: 'php:7.2'

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: 'mysqldb:mysql'

# The size of the persistent disk of the application (in MB).
disk: 1024

# The 'mounts' describe writable, persistent filesystem mounts in the application.
# The keys are directory paths relative to the application root. The values are a
# mount definition. In this case, `web-files` is just a unique name for the mount.
mounts:
  'tmp':
    source: local
    source_path: tmp

# The configuration of the application when it is exposed to the web.
web:
  locations:
    '/':
      # The public directory of the application relative to its root.
      root: ''
      # The front-controller script which determines where to send
      # non-static requests.
      passthru: '/index.php'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # build: |
      # curl -o - --compressed https://download.db-ip.com/free/dbip-city-lite-`date +"%Y"`-`date +"%m"`.mmdb.gz | gunzip -c > misc/DBIP-City-Lite.mmdb
    # Run composer ourself to not install development dependencies.
    deploy: |
      ./console core:update --yes

# crons:
#   # Run the archive cron task once per hour.
#   drupal:
#     spec: '0 * * * *'
#     cmd: './console core:archive'
