name: 'Handle inactive PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          debug-only: true
          start-date: 2021-03-01T00:00:00Z
          days-before-pr-stale: 14
          days-before-pr-close: -1
          days-before-issue-stale: -1
          days-before-issue-close: -1
          exempt-pr-labels: Do not close
          stale-pr-message: If you don't want this PR to be closed automatically in 28 days then you need to assign the label 'Do not close'.
          stale-pr-label: Stale
